# ruff: noqa: E501
"""Generated by m365-compile-contracts; do not edit manually."""

import json
from typing import Any, Final

CONTROL_LIBRARY_VERSION: Final = '1.0.0'
CONTROL_MANIFEST_DIGEST: Final = (
    'sha256:aab4fbabbf8757b6b2bf54bec9f23e60849807f65b5c0ec7deedbc9d9d7217d1'
)
CONTROL_DEFINITIONS: Final[dict[str, dict[str, Any]]] = json.loads(
    r'''{
  "entra.applications.active_credential_count": {
    "definition_version": "1.0.0",
    "description": "Determine whether active application credential counts remain within customer-governed limits.",
    "evaluator_id": "ENTRA_APPLICATION_ACTIVE_CREDENTIAL_COUNT_V1",
    "evidence_requirements": [
      {
        "completeness_required": "complete_for_signed_targets",
        "evidence_domains": [
          "applications"
        ],
        "requirement_id": "application_credential_inventory",
        "source_contract_id": "entra.app_credentials.posture.snapshot"
      }
    ],
    "expected_condition": "application_active_credential_counts_match_policy",
    "lifecycle": {
      "deprecated_at": null,
      "introduced_in_library_version": "1.0.0",
      "retired_at": null,
      "state": "active",
      "successor_control_id": null
    },
    "limitation_codes": [
      "credential_availability_not_inferred",
      "does_not_prove_legal_compliance",
      "signed_target_set_only"
    ],
    "mapping_ids": [
      "eu.nis2.article-21-2-i",
      "microsoft.apps.credential-hygiene"
    ],
    "operator_action_id": "review_application_credential_counts",
    "title": "Application active credential count"
  },
  "entra.applications.credential_expiry_posture": {
    "definition_version": "1.0.0",
    "description": "Determine whether application credential validity windows and expiry remain within customer-governed policy.",
    "evaluator_id": "ENTRA_APPLICATION_CREDENTIAL_EXPIRY_POSTURE_V1",
    "evidence_requirements": [
      {
        "completeness_required": "complete_for_signed_targets",
        "evidence_domains": [
          "applications"
        ],
        "requirement_id": "application_credential_inventory",
        "source_contract_id": "entra.app_credentials.posture.snapshot"
      }
    ],
    "expected_condition": "application_credentials_meet_expiry_policy",
    "lifecycle": {
      "deprecated_at": null,
      "introduced_in_library_version": "1.0.0",
      "retired_at": null,
      "state": "active",
      "successor_control_id": null
    },
    "limitation_codes": [
      "does_not_prove_legal_compliance",
      "signed_target_set_only"
    ],
    "mapping_ids": [
      "eu.nis2.article-21-2-i",
      "microsoft.apps.credential-hygiene"
    ],
    "operator_action_id": "review_application_credential_expiry",
    "title": "Application credential expiry posture"
  },
  "entra.applications.owner_coverage": {
    "definition_version": "1.0.0",
    "description": "Determine whether signed application targets meet the customer-governed minimum owner coverage.",
    "evaluator_id": "ENTRA_APPLICATION_OWNER_COVERAGE_V1",
    "evidence_requirements": [
      {
        "completeness_required": "complete_for_signed_targets",
        "evidence_domains": [
          "owners"
        ],
        "requirement_id": "application_owner_inventory",
        "source_contract_id": "entra.app_credentials.posture.snapshot"
      }
    ],
    "expected_condition": "application_owner_count_meets_policy",
    "lifecycle": {
      "deprecated_at": null,
      "introduced_in_library_version": "1.0.0",
      "retired_at": null,
      "state": "active",
      "successor_control_id": null
    },
    "limitation_codes": [
      "does_not_prove_legal_compliance",
      "organizational_process_not_evaluated",
      "signed_target_set_only"
    ],
    "mapping_ids": [
      "eu.nis2.article-21-2-i",
      "microsoft.apps.owner-review"
    ],
    "operator_action_id": "review_application_owners",
    "title": "Application owner coverage"
  },
  "entra.applications.password_credential_policy": {
    "definition_version": "1.0.0",
    "description": "Determine whether password credential use on signed application targets matches customer-governed policy.",
    "evaluator_id": "ENTRA_APPLICATION_PASSWORD_CREDENTIAL_POLICY_V1",
    "evidence_requirements": [
      {
        "completeness_required": "complete_for_signed_targets",
        "evidence_domains": [
          "applications"
        ],
        "requirement_id": "application_credential_inventory",
        "source_contract_id": "entra.app_credentials.posture.snapshot"
      }
    ],
    "expected_condition": "application_password_credentials_match_policy",
    "lifecycle": {
      "deprecated_at": null,
      "introduced_in_library_version": "1.0.0",
      "retired_at": null,
      "state": "active",
      "successor_control_id": null
    },
    "limitation_codes": [
      "does_not_prove_legal_compliance",
      "signed_target_set_only"
    ],
    "mapping_ids": [
      "eu.nis2.article-21-2-i",
      "microsoft.apps.credential-hygiene"
    ],
    "operator_action_id": "review_application_password_credentials",
    "title": "Application password credential policy"
  },
  "entra.applications.permission_contract_closure": {
    "definition_version": "1.0.0",
    "description": "Determine whether observed application permissions match the exact closure of signed compiled contracts.",
    "evaluator_id": "ENTRA_APPLICATION_PERMISSION_CONTRACT_CLOSURE_V1",
    "evidence_requirements": [
      {
        "completeness_required": "complete_for_signed_targets",
        "evidence_domains": [
          "application_grants",
          "delegated_grants",
          "resource_catalog",
          "targets"
        ],
        "requirement_id": "application_permission_grants",
        "source_contract_id": "entra.permission_grants.drift.snapshot"
      }
    ],
    "expected_condition": "application_permissions_match_compiled_contracts",
    "lifecycle": {
      "deprecated_at": null,
      "introduced_in_library_version": "1.0.0",
      "retired_at": null,
      "state": "active",
      "successor_control_id": null
    },
    "limitation_codes": [
      "does_not_prove_legal_compliance",
      "signed_target_set_only"
    ],
    "mapping_ids": [
      "eu.nis2.article-21-2-i",
      "microsoft.apps.least-privilege"
    ],
    "operator_action_id": "review_application_permissions",
    "title": "Application permission contract closure"
  },
  "entra.conditional_access.mfa_policy_coverage": {
    "definition_version": "1.0.0",
    "description": "Determine whether complete Conditional Access evidence proves the required multifactor authentication policy coverage.",
    "evaluator_id": "ENTRA_CA_MFA_POLICY_COVERAGE_V1",
    "evidence_requirements": [
      {
        "completeness_required": "complete",
        "evidence_domains": [
          "conditional_access"
        ],
        "requirement_id": "conditional_access_policies",
        "source_contract_id": "entra.identity_governance.posture.snapshot"
      }
    ],
    "expected_condition": "mfa_policy_covers_required_identities_and_resources",
    "lifecycle": {
      "deprecated_at": null,
      "introduced_in_library_version": "1.0.0",
      "retired_at": null,
      "state": "active",
      "successor_control_id": null
    },
    "limitation_codes": [
      "does_not_prove_legal_compliance",
      "organizational_process_not_evaluated",
      "requires_complete_conditional_access_evidence"
    ],
    "mapping_ids": [
      "eu.nis2.article-21-2-j",
      "microsoft.ca.mfa-all-users"
    ],
    "operator_action_id": "review_mfa_coverage",
    "title": "Conditional Access MFA policy coverage"
  },
  "entra.directory_roles.permanent_active_assignment": {
    "definition_version": "1.0.0",
    "description": "Determine whether complete role evidence contains permanent active directory-role assignments without an exact approved exception.",
    "evaluator_id": "ENTRA_DIRECTORY_ROLE_PERMANENT_ACTIVE_ASSIGNMENT_V1",
    "evidence_requirements": [
      {
        "completeness_required": "complete",
        "evidence_domains": [
          "active_role_assignments",
          "eligible_role_assignments",
          "permanent_role_assignments"
        ],
        "requirement_id": "directory_role_assignments",
        "source_contract_id": "entra.identity_governance.posture.snapshot"
      }
    ],
    "expected_condition": "no_unexcepted_permanent_active_role_assignment",
    "lifecycle": {
      "deprecated_at": null,
      "introduced_in_library_version": "1.0.0",
      "retired_at": null,
      "state": "active",
      "successor_control_id": null
    },
    "limitation_codes": [
      "does_not_prove_legal_compliance",
      "organizational_process_not_evaluated",
      "pim_configuration_not_evaluated"
    ],
    "mapping_ids": [
      "eu.nis2.article-21-2-i",
      "microsoft.pim.zero-permanent-active"
    ],
    "operator_action_id": "review_permanent_role_assignments",
    "title": "Permanent active directory-role assignment"
  },
  "entra.profiles.contract_closure": {
    "definition_version": "1.0.0",
    "description": "Determine whether contracts enabled in the active profile have current bounded operational evidence.",
    "evaluator_id": "ENTRA_PROFILE_CONTRACT_CLOSURE_V1",
    "evidence_requirements": [
      {
        "completeness_required": "complete_for_active_profile",
        "evidence_domains": [
          "audit_evidence",
          "policy_lifecycle",
          "profile_contracts"
        ],
        "requirement_id": "active_profile_contract_evidence",
        "source_contract_id": "entra.profile_debt.posture.snapshot"
      }
    ],
    "expected_condition": "active_profile_contracts_have_current_evidence",
    "lifecycle": {
      "deprecated_at": null,
      "introduced_in_library_version": "1.0.0",
      "retired_at": null,
      "state": "active",
      "successor_control_id": null
    },
    "limitation_codes": [
      "active_profile_only",
      "does_not_prove_legal_compliance",
      "historical_usage_not_evaluated"
    ],
    "mapping_ids": [
      "eu.nis2.article-21-2-f"
    ],
    "operator_action_id": "review_profile_contract_closure",
    "title": "Active profile contract closure"
  },
  "entra.profiles.resource_fence_closure": {
    "definition_version": "1.0.0",
    "description": "Determine whether resource fences for the active profile are closed across runtime and signed Governance evidence.",
    "evaluator_id": "ENTRA_PROFILE_RESOURCE_FENCE_CLOSURE_V1",
    "evidence_requirements": [
      {
        "completeness_required": "complete_for_active_profile",
        "evidence_domains": [
          "profile_contracts",
          "resource_fences"
        ],
        "requirement_id": "active_profile_resource_fences",
        "source_contract_id": "entra.profile_debt.posture.snapshot"
      }
    ],
    "expected_condition": "active_profile_resource_fences_are_closed",
    "lifecycle": {
      "deprecated_at": null,
      "introduced_in_library_version": "1.0.0",
      "retired_at": null,
      "state": "active",
      "successor_control_id": null
    },
    "limitation_codes": [
      "active_profile_only",
      "does_not_prove_legal_compliance",
      "organizational_process_not_evaluated"
    ],
    "mapping_ids": [
      "eu.nis2.article-21-2-f",
      "eu.nis2.article-21-2-i"
    ],
    "operator_action_id": "review_profile_resource_fences",
    "title": "Active profile resource-fence closure"
  },
  "entra.profiles.scope_closure": {
    "definition_version": "1.0.0",
    "description": "Determine whether effective delegated scopes match the exact permission closure of the active signed profile.",
    "evaluator_id": "ENTRA_PROFILE_SCOPE_CLOSURE_V1",
    "evidence_requirements": [
      {
        "completeness_required": "complete_for_active_profile",
        "evidence_domains": [
          "permission_grants",
          "profile_contracts",
          "token_scopes"
        ],
        "requirement_id": "active_profile_scope_evidence",
        "source_contract_id": "entra.profile_debt.posture.snapshot"
      }
    ],
    "expected_condition": "active_profile_scopes_match_contract_closure",
    "lifecycle": {
      "deprecated_at": null,
      "introduced_in_library_version": "1.0.0",
      "retired_at": null,
      "state": "active",
      "successor_control_id": null
    },
    "limitation_codes": [
      "active_profile_only",
      "does_not_prove_legal_compliance"
    ],
    "mapping_ids": [
      "eu.nis2.article-21-2-f",
      "eu.nis2.article-21-2-i",
      "microsoft.apps.least-privilege"
    ],
    "operator_action_id": "review_profile_scope_closure",
    "title": "Active profile scope closure"
  }
}'''
)
CONTROL_FRAMEWORK_SOURCES: Final[dict[str, dict[str, Any]]] = json.loads(
    r'''{
  "eu.nis2.directive-2022-2555": {
    "publisher": "European Union",
    "source_id": "eu.nis2.directive-2022-2555",
    "source_kind": "eu_legislation",
    "source_version": "2022-12-14",
    "title": "Directive on measures for a high common level of cybersecurity across the Union",
    "url": "https://eur-lex.europa.eu/eli/dir/2022/2555/oj/eng",
    "verification_status": "verified",
    "verified_at": "2026-07-27"
  },
  "microsoft.entra.app-security-20250620": {
    "publisher": "Microsoft",
    "source_id": "microsoft.entra.app-security-20250620",
    "source_kind": "microsoft_security_guidance",
    "source_version": "2025-06-20",
    "title": "Security best practices for application properties in Microsoft Entra ID",
    "url": "https://learn.microsoft.com/en-us/entra/identity-platform/security-best-practices-for-app-registration",
    "verification_status": "verified",
    "verified_at": "2026-07-27"
  },
  "microsoft.entra.ca-mfa-20260324": {
    "publisher": "Microsoft",
    "source_id": "microsoft.entra.ca-mfa-20260324",
    "source_kind": "microsoft_security_guidance",
    "source_version": "2026-03-24",
    "title": "Require multifactor authentication for all users",
    "url": "https://learn.microsoft.com/en-us/entra/identity/conditional-access/policy-all-users-mfa-strength",
    "verification_status": "verified",
    "verified_at": "2026-07-27"
  },
  "microsoft.entra.pim-plan-20260423": {
    "publisher": "Microsoft",
    "source_id": "microsoft.entra.pim-plan-20260423",
    "source_kind": "microsoft_security_guidance",
    "source_version": "2026-04-23",
    "title": "Plan a Privileged Identity Management deployment",
    "url": "https://learn.microsoft.com/en-us/entra/id-governance/privileged-identity-management/pim-deployment-plan",
    "verification_status": "verified",
    "verified_at": "2026-07-27"
  }
}'''
)
CONTROL_FRAMEWORK_MAPPINGS: Final[dict[str, dict[str, Any]]] = json.loads(
    r'''{
  "eu.nis2.article-21-2-f": {
    "limitation_codes": [
      "does_not_prove_legal_compliance",
      "organizational_process_not_evaluated"
    ],
    "mapping_id": "eu.nis2.article-21-2-f",
    "organizational_coverage": "supporting",
    "published": true,
    "reference": "Article 21(2)(f), policies and procedures to assess effectiveness",
    "relationship": "supporting",
    "source_id": "eu.nis2.directive-2022-2555",
    "technical_coverage": "partial",
    "verification_status": "verified"
  },
  "eu.nis2.article-21-2-i": {
    "limitation_codes": [
      "does_not_prove_legal_compliance",
      "organizational_process_not_evaluated"
    ],
    "mapping_id": "eu.nis2.article-21-2-i",
    "organizational_coverage": "supporting",
    "published": true,
    "reference": "Article 21(2)(i), human resources security, access control and asset management",
    "relationship": "supporting",
    "source_id": "eu.nis2.directive-2022-2555",
    "technical_coverage": "partial",
    "verification_status": "verified"
  },
  "eu.nis2.article-21-2-j": {
    "limitation_codes": [
      "does_not_prove_legal_compliance",
      "organizational_process_not_evaluated"
    ],
    "mapping_id": "eu.nis2.article-21-2-j",
    "organizational_coverage": "supporting",
    "published": true,
    "reference": "Article 21(2)(j), multifactor or continuous authentication where appropriate",
    "relationship": "supporting",
    "source_id": "eu.nis2.directive-2022-2555",
    "technical_coverage": "partial",
    "verification_status": "verified"
  },
  "microsoft.apps.credential-hygiene": {
    "limitation_codes": [
      "does_not_prove_legal_compliance",
      "organizational_process_not_evaluated"
    ],
    "mapping_id": "microsoft.apps.credential-hygiene",
    "organizational_coverage": "none",
    "published": true,
    "reference": "Credentials, including certificates and secrets",
    "relationship": "direct",
    "source_id": "microsoft.entra.app-security-20250620",
    "technical_coverage": "direct",
    "verification_status": "verified"
  },
  "microsoft.apps.least-privilege": {
    "limitation_codes": [
      "does_not_prove_legal_compliance",
      "organizational_process_not_evaluated"
    ],
    "mapping_id": "microsoft.apps.least-privilege",
    "organizational_coverage": "none",
    "published": true,
    "reference": "Permissions, follow least privilege principles",
    "relationship": "direct",
    "source_id": "microsoft.entra.app-security-20250620",
    "technical_coverage": "direct",
    "verification_status": "verified"
  },
  "microsoft.apps.owner-review": {
    "limitation_codes": [
      "does_not_prove_legal_compliance",
      "organizational_process_not_evaluated"
    ],
    "mapping_id": "microsoft.apps.owner-review",
    "organizational_coverage": "supporting",
    "published": true,
    "reference": "App ownership configuration",
    "relationship": "supporting",
    "source_id": "microsoft.entra.app-security-20250620",
    "technical_coverage": "partial",
    "verification_status": "verified"
  },
  "microsoft.ca.mfa-all-users": {
    "limitation_codes": [
      "does_not_prove_legal_compliance",
      "organizational_process_not_evaluated",
      "requires_complete_conditional_access_evidence"
    ],
    "mapping_id": "microsoft.ca.mfa-all-users",
    "organizational_coverage": "none",
    "published": true,
    "reference": "Require multifactor authentication for all users",
    "relationship": "direct",
    "source_id": "microsoft.entra.ca-mfa-20260324",
    "technical_coverage": "direct",
    "verification_status": "verified"
  },
  "microsoft.pim.zero-permanent-active": {
    "limitation_codes": [
      "does_not_prove_legal_compliance",
      "pim_configuration_not_evaluated"
    ],
    "mapping_id": "microsoft.pim.zero-permanent-active",
    "organizational_coverage": "none",
    "published": true,
    "reference": "Type of assignments, zero permanently active assignments outside emergency access",
    "relationship": "direct",
    "source_id": "microsoft.entra.pim-plan-20260423",
    "technical_coverage": "direct",
    "verification_status": "verified"
  }
}'''
)
