"""Generated by m365-compile-contracts; do not edit manually."""

import json
from typing import Any, Final

CONTRACT_MANIFEST_DIGEST: Final = (
    'sha256:2a658b65f9358b2198fd4a49688d4489321c23129121b8c5b4b0f543a0133907'
)
CONTRACT_DEFINITIONS: Final[dict[str, dict[str, Any]]] = json.loads(
    r'''{
  "entra.app_credentials.posture.snapshot": {
    "authorization_mode": "automatic_read",
    "compensation": "not_applicable",
    "delegated_scopes": [
      "Application.Read.All"
    ],
    "endpoint": "/applications/{application_id}",
    "input_schema": {
      "additionalProperties": false,
      "properties": {},
      "type": "object"
    },
    "method": "GET",
    "module": "assurance",
    "operator_roles": [
      "Directory Readers",
      "Global Reader"
    ],
    "output_fields": [
      "status",
      "contract_digest",
      "policy_digest",
      "snapshot_reference",
      "coverage_status",
      "baseline_id",
      "baseline_version",
      "targets",
      "findings",
      "writes_performed"
    ],
    "resource_fences": [
      "session_tenant_only",
      "signed_policy_tenant_only",
      "signed_application_targets",
      "local_application_allowlist",
      "bounded_complete_collections",
      "keyed_deployment_local_references",
      "no_raw_resource_ids_in_mcp_output",
      "no_credential_material_in_mcp_output"
    ],
    "risk_tier": "T0",
    "tool_name": "m365_get_entra_app_credential_posture",
    "verification": "resource_observed"
  },
  "entra.conditional_access.policies.read": {
    "authorization_mode": "automatic_read",
    "compensation": "not_applicable",
    "delegated_scopes": [
      "Policy.Read.All"
    ],
    "endpoint": "/identity/conditionalAccess/policies",
    "input_schema": {
      "additionalProperties": false,
      "properties": {
        "cursor": {
          "maxLength": 8000,
          "minLength": 40,
          "type": [
            "string",
            "null"
          ]
        },
        "limit": {
          "maximum": 50,
          "minimum": 1,
          "type": "integer"
        }
      },
      "type": "object"
    },
    "method": "GET",
    "module": "governance",
    "operator_roles": [
      "Conditional Access Administrator",
      "Global Reader",
      "Security Reader"
    ],
    "output_fields": [
      "id",
      "displayName",
      "state",
      "createdDateTime",
      "modifiedDateTime"
    ],
    "resource_fences": [
      "session_tenant_only",
      "bounded_collection"
    ],
    "risk_tier": "T0",
    "tool_name": "m365_list_conditional_access_policies",
    "verification": "resource_observed"
  },
  "entra.identity_governance.posture.snapshot": {
    "authorization_mode": "automatic_read",
    "compensation": "not_applicable",
    "delegated_scopes": [
      "Policy.Read.All",
      "RoleManagement.Read.Directory"
    ],
    "endpoint": "/identity/conditionalAccess/policies",
    "input_schema": {
      "additionalProperties": false,
      "properties": {},
      "type": "object"
    },
    "method": "GET",
    "module": "assurance",
    "operator_roles": [
      "Global Reader"
    ],
    "output_fields": [
      "status",
      "contract_digest",
      "policy_digest",
      "snapshot_reference",
      "coverage_status",
      "baseline",
      "domains",
      "findings",
      "writes_performed"
    ],
    "resource_fences": [
      "session_tenant_only",
      "signed_policy_tenant_only",
      "bounded_complete_collections",
      "keyed_deployment_local_digests",
      "no_raw_resource_values_in_mcp_output"
    ],
    "risk_tier": "T0",
    "tool_name": "m365_get_entra_identity_governance_posture",
    "verification": "resource_observed"
  },
  "entra.organization.summary.read": {
    "authorization_mode": "automatic_read",
    "compensation": "not_applicable",
    "delegated_scopes": [
      "Organization.Read.All"
    ],
    "endpoint": "/organization",
    "input_schema": {
      "additionalProperties": false,
      "properties": {},
      "type": "object"
    },
    "method": "GET",
    "module": "organization",
    "operator_roles": [
      "Global Reader"
    ],
    "output_fields": [
      "id",
      "displayName",
      "tenantType",
      "verifiedDomains"
    ],
    "resource_fences": [
      "session_tenant_only"
    ],
    "risk_tier": "T0",
    "tool_name": "m365_get_organization",
    "verification": "resource_observed"
  },
  "entra.permission_grants.drift.snapshot": {
    "authorization_mode": "automatic_read",
    "compensation": "not_applicable",
    "delegated_scopes": [
      "Directory.Read.All"
    ],
    "endpoint": "/oauth2PermissionGrants",
    "input_schema": {
      "additionalProperties": false,
      "properties": {},
      "type": "object"
    },
    "method": "GET",
    "module": "assurance",
    "operator_roles": [
      "Directory Readers",
      "Global Reader"
    ],
    "output_fields": [
      "status",
      "contract_digest",
      "policy_digest",
      "snapshot_reference",
      "coverage_status",
      "baseline_id",
      "baseline_version",
      "targets",
      "findings",
      "writes_performed"
    ],
    "resource_fences": [
      "session_tenant_only",
      "signed_policy_tenant_only",
      "signed_service_principal_targets",
      "local_service_principal_allowlist",
      "bounded_complete_collections",
      "keyed_deployment_local_references",
      "no_raw_resource_ids_in_mcp_output"
    ],
    "risk_tier": "T0",
    "tool_name": "m365_get_entra_permission_grant_drift",
    "verification": "resource_observed"
  },
  "entra.role_assignments.read": {
    "authorization_mode": "automatic_read",
    "compensation": "not_applicable",
    "delegated_scopes": [
      "RoleManagement.Read.Directory"
    ],
    "endpoint": "/roleManagement/directory/roleAssignments",
    "input_schema": {
      "additionalProperties": false,
      "properties": {
        "cursor": {
          "maxLength": 8000,
          "minLength": 40,
          "type": [
            "string",
            "null"
          ]
        },
        "limit": {
          "maximum": 50,
          "minimum": 1,
          "type": "integer"
        }
      },
      "type": "object"
    },
    "method": "GET",
    "module": "governance",
    "operator_roles": [
      "Directory Readers",
      "Global Reader",
      "Privileged Role Administrator"
    ],
    "output_fields": [
      "id",
      "principalId",
      "roleDefinitionId",
      "directoryScopeId"
    ],
    "resource_fences": [
      "session_tenant_only",
      "bounded_collection"
    ],
    "risk_tier": "T0",
    "tool_name": "m365_list_directory_role_assignments",
    "verification": "resource_observed"
  },
  "entra.user.operational_profile.read": {
    "authorization_mode": "automatic_read",
    "compensation": "not_applicable",
    "delegated_scopes": [
      "User.Read.All"
    ],
    "endpoint": "/users/{user_id}",
    "input_schema": {
      "additionalProperties": false,
      "properties": {
        "user_id": {
          "format": "uuid",
          "type": "string"
        }
      },
      "required": [
        "user_id"
      ],
      "type": "object"
    },
    "method": "GET",
    "module": "users_admin",
    "operator_roles": [
      "Directory Readers",
      "Global Reader",
      "User Administrator"
    ],
    "output_fields": [
      "id",
      "userType",
      "onPremisesSyncEnabled",
      "department",
      "jobTitle",
      "officeLocation"
    ],
    "resource_fences": [
      "session_tenant_only",
      "allowlisted_target_user"
    ],
    "risk_tier": "T0",
    "tool_name": "m365_get_allowed_user",
    "verification": "resource_observed"
  },
  "entra.user.operational_profile.update": {
    "authorization_mode": "standing_policy",
    "compensation": "conditional_restore",
    "delegated_scopes": [
      "GroupMember.Read.All",
      "RoleManagement.Read.Directory",
      "User.ReadUpdate.All"
    ],
    "endpoint": "/users/{user_id}",
    "input_schema": {
      "additionalProperties": false,
      "properties": {
        "department": {
          "maxLength": 128,
          "minLength": 1,
          "type": "string"
        },
        "idempotency_key": {
          "format": "uuid",
          "type": "string"
        },
        "job_title": {
          "maxLength": 128,
          "minLength": 1,
          "type": "string"
        },
        "office_location": {
          "maxLength": 128,
          "minLength": 1,
          "type": "string"
        },
        "user_id": {
          "format": "uuid",
          "type": "string"
        }
      },
      "required": [
        "idempotency_key",
        "user_id"
      ],
      "type": "object"
    },
    "method": "PATCH",
    "module": "users_admin",
    "operator_roles": [
      "Global Reader",
      "User Administrator"
    ],
    "output_fields": [
      "status",
      "reason_code",
      "operator_action",
      "authorization_mode",
      "authorization_basis",
      "changed_fields",
      "verification",
      "receipt_reference",
      "change_record"
    ],
    "resource_fences": [
      "session_tenant_only",
      "allowlisted_target_user",
      "signed_policy_user_allowlist",
      "protected_user_denylist",
      "one_target_per_operation",
      "member_users_only",
      "cloud_managed_users_only",
      "non_privileged_users_only"
    ],
    "risk_tier": "T1",
    "tool_name": "m365_update_entra_user_operational_profile",
    "verification": "strong_readback"
  }
}'''
)
