"""Generated by m365-compile-contracts; do not edit manually."""

import json
from typing import Any, Final

PLAYBOOK_MANIFEST_DIGEST: Final = (
    'sha256:13a3dada2e106bc8f56f35301e4b57e601a75668adebe73be07b829d39819ca4'
)
PLAYBOOK_DEFINITIONS: Final[dict[str, dict[str, Any]]] = json.loads(
    r'''{
  "entra.workload_identity.readiness.playbook": {
    "authorization_mode": "automatic_read",
    "compensation": "not_applicable",
    "delegated_scopes": [
      "Application.Read.All",
      "Directory.Read.All"
    ],
    "failure_mode": "halt_not_evaluated",
    "module": "assurance",
    "nodes": [
      {
        "contract_id": "entra.app_credentials.posture.snapshot",
        "depends_on": [],
        "id": "application_credentials"
      },
      {
        "contract_id": "entra.permission_grants.drift.snapshot",
        "depends_on": [],
        "id": "permission_grants"
      }
    ],
    "operator_roles": [
      "Directory Readers",
      "Global Reader"
    ],
    "output_fields": [
      "active_profile",
      "admin_consent_is_manual",
      "authorization_basis",
      "authorization_mode",
      "captured_at",
      "contract_manifest_digest",
      "coverage_status",
      "findings",
      "nodes",
      "playbook_digest",
      "playbook_id",
      "playbook_manifest_digest",
      "policy_digest",
      "run_id",
      "schema_version",
      "status",
      "targets",
      "tenant_namespace",
      "writes_performed"
    ],
    "risk_tier": "T0",
    "tool_name": "m365_get_entra_workload_identity_readiness",
    "writes_permitted": false
  }
}'''
)
