"""Deterministic build-time compiler for the signed global contract manifest."""

from __future__ import annotations

import argparse
import hashlib
import json
import tomllib
from pathlib import Path
from typing import Any
from uuid import NAMESPACE_URL, uuid5

from .contract_manifest import (
    ContractManifest,
    canonical_json,
    load_global_manifest,
    sha256_digest,
)

COMPILER_VERSION = "1.0"


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _generated_python(manifest: ContractManifest) -> str:
    contracts = {
        item.id: {
            "tool_name": item.tool_name,
            "module": item.module,
            "method": item.graph.method,
            "endpoint": item.graph.endpoint,
            "input_schema": item.input_schema,
            "output_fields": item.output_fields,
            "delegated_scopes": item.permissions.delegated_scopes,
            "operator_roles": item.permissions.operator_roles,
            "risk_tier": item.risk_tier.value,
            "authorization_mode": item.authorization_mode.value,
            "resource_fences": item.resource_fences,
            "verification": item.verification.value,
            "compensation": item.compensation.value,
        }
        for item in manifest.contracts
    }
    rendered = json.dumps(
        contracts,
        indent=2,
        ensure_ascii=True,
        sort_keys=True,
    )
    digest = sha256_digest(manifest)
    return (
        '"""Generated by m365-compile-contracts; do not edit manually."""\n\n'
        "import json\n"
        "from typing import Any, Final\n\n"
        "CONTRACT_MANIFEST_DIGEST: Final = (\n"
        f"    {digest!r}\n"
        ")\n"
        "CONTRACT_DEFINITIONS: Final[dict[str, dict[str, Any]]] = json.loads(\n"
        f"    r'''{rendered}'''\n"
        ")\n"
    )


def _permission_matrix(manifest: ContractManifest) -> str:
    lines = [
        "# Compiled contract matrix",
        "",
        "Generated from the signed, tenant-neutral global manifest.",
        "",
        "| Contract | Tool | Graph call | Tier | Authorization | Delegated scopes |",
        "|---|---|---|---|---|---|",
    ]
    for item in manifest.contracts:
        scopes = "<br>".join(f"`{scope}`" for scope in item.permissions.delegated_scopes)
        lines.append(
            f"| `{item.id}` | `{item.tool_name}` | "
            f"`{item.graph.method} {item.graph.endpoint}` | `{item.risk_tier.value}` | "
            f"`{item.authorization_mode.value}` | {scopes} |"
        )
    lines.extend(
        [
            "",
            "Permissions are informational build output. The server cannot add delegated",
            "permissions or grant tenant consent; an administrator must do that manually.",
            "",
        ]
    )
    return "\n".join(lines)


def _dependency_components(root: Path) -> list[dict[str, Any]]:
    lock = tomllib.loads((root / "uv.lock").read_text())
    components: list[dict[str, Any]] = []
    seen: set[tuple[str, str]] = set()
    for package in lock["package"]:
        name = str(package["name"]).lower().replace("_", "-")
        version = str(package.get("version", ""))
        if (
            not version
            or name == "m365-secure-mcp"
            or not isinstance(package.get("source"), dict)
            or "registry" not in package["source"]
            or (name, version) in seen
        ):
            continue
        seen.add((name, version))
        components.append(
            {
                "type": "library",
                "bom-ref": f"pkg:pypi/{name}@{version}",
                "name": name,
                "version": version,
                "purl": f"pkg:pypi/{name}@{version}",
                "properties": [
                    {
                        "name": "m365-secure-mcp:source",
                        "value": "uv.lock",
                    }
                ],
            }
        )
    return sorted(
        components,
        key=lambda item: (str(item["name"]), str(item["version"])),
    )


def compile_outputs(
    manifest: ContractManifest,
    *,
    root: Path,
) -> dict[Path, bytes]:
    manifest_digest = sha256_digest(manifest)
    lock_digest = (
        "sha256:"
        + hashlib.sha256((root / "uv.lock").read_bytes()).hexdigest()
    )
    contract_digests = {
        item.id: sha256_digest(item)
        for item in manifest.contracts
    }
    tests = {
        "schema_version": "1.0",
        "manifest_digest": manifest_digest,
        "assertions": [
            {
                "contract_id": item.id,
                "method": item.graph.method,
                "endpoint": item.graph.endpoint,
                "input_fields": sorted(item.input_schema["properties"]),
                "delegated_scopes": item.permissions.delegated_scopes,
                "authorization_mode": item.authorization_mode.value,
                "risk_tier": item.risk_tier.value,
            }
            for item in manifest.contracts
        ],
    }
    provenance = {
        "schema_version": "1.0",
        "builder": "m365_secure_mcp.contract_compiler",
        "compiler_version": COMPILER_VERSION,
        "source_repository": "https://github.com/bugroo/m365-secure-mcp",
        "source_revision": "release-attestation-required",
        "manifest_digest": manifest_digest,
        "manifest_signature_required": True,
        "dependency_lock_digest": lock_digest,
        "runtime_tool_generation": False,
    }
    sbom_serial = uuid5(
        NAMESPACE_URL,
        f"m365-secure-mcp:{manifest_digest}:{lock_digest}",
    )
    sbom = {
        "bomFormat": "CycloneDX",
        "specVersion": "1.6",
        "serialNumber": f"urn:uuid:{sbom_serial}",
        "version": 1,
        "metadata": {
            "component": {
                "type": "application",
                "name": "m365-secure-mcp",
                "version": tomllib.loads(
                    (root / "pyproject.toml").read_text()
                )["project"]["version"],
            }
        },
        "components": _dependency_components(root),
    }

    def encoded(value: object) -> bytes:
        return (
            json.dumps(value, indent=2, ensure_ascii=False, sort_keys=True) + "\n"
        ).encode()

    return {
        root / "src/m365_secure_mcp/_generated_contracts.py": (
            _generated_python(manifest).encode()
        ),
        root / "docs/CONTRACT_MATRIX.md": _permission_matrix(manifest).encode(),
        root / "contract-artifacts/contract-digests.json": encoded(
            {
                "schema_version": "1.0",
                "manifest_digest": manifest_digest,
                "contracts": contract_digests,
            }
        ),
        root / "contract-artifacts/contract-tests.json": encoded(tests),
        root / "contract-artifacts/provenance.json": encoded(provenance),
        root / "contract-artifacts/sbom.cdx.json": encoded(sbom),
    }


def write_outputs(outputs: dict[Path, bytes]) -> None:
    for path, payload in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(payload)


def check_outputs(outputs: dict[Path, bytes]) -> list[str]:
    mismatches: list[str] = []
    for path, expected in outputs.items():
        try:
            actual = path.read_bytes()
        except OSError:
            mismatches.append(str(path))
            continue
        if actual != expected:
            mismatches.append(str(path))
    return mismatches


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="m365-compile-contracts",
        description=(
            "Verify the signed global manifest and generate deterministic internal "
            "contracts, permission docs, tests, provenance, and CycloneDX SBOM."
        ),
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if committed generated artifacts differ from the signed manifest",
    )
    return parser


def main() -> None:
    args = _parser().parse_args()
    root = _repo_root()
    manifest = load_global_manifest()
    outputs = compile_outputs(manifest, root=root)
    if args.check:
        mismatches = check_outputs(outputs)
        if mismatches:
            raise SystemExit(
                "generated contract artifacts are stale:\n" + "\n".join(mismatches)
            )
        print(
            json.dumps(
                {
                    "status": "verified",
                    "manifest_digest": sha256_digest(manifest),
                    "artifacts": len(outputs),
                },
                indent=2,
            )
        )
        return
    write_outputs(outputs)
    print(
        json.dumps(
            {
                "status": "generated",
                "manifest_digest": sha256_digest(manifest),
                "artifacts": len(outputs),
                "manifest_bytes": len(canonical_json(manifest)),
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
