"""Deterministic build-time compiler for the signed global contract manifest."""

from __future__ import annotations

import argparse
import hashlib
import json
import tomllib
from pathlib import Path
from typing import Any
from uuid import NAMESPACE_URL, uuid5

from .contract_manifest import (
    ContractManifest,
    ContractManifestV2,
    canonical_json,
    contract_effect,
    effect_model_digest,
    effect_model_document,
    load_global_manifest,
    parse_contract_manifest,
    sha256_digest,
)
from .control_compatibility import (
    ControlCompatibilityMetadata,
    control_compatibility_digest,
    load_control_compatibility_metadata,
)
from .control_manifest import ControlManifest, load_global_control_manifest
from .playbook_manifest import PlaybookManifest, load_global_playbook_manifest

COMPILER_VERSION = "1.6"


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _generated_python(manifest: ContractManifest) -> str:
    model_digest = effect_model_digest()
    contracts = {
        item.id: {
            "tool_name": item.tool_name,
            "module": item.module,
            "method": item.graph.method,
            "endpoint": item.graph.endpoint,
            "effect": contract_effect(item).value,
            "input_schema": item.input_schema,
            "output_fields": item.output_fields,
            "delegated_scopes": item.permissions.delegated_scopes,
            "operator_roles": item.permissions.operator_roles,
            "risk_tier": item.risk_tier.value,
            "authorization_mode": item.authorization_mode.value,
            "resource_fences": item.resource_fences,
            "verification": item.verification.value,
            "compensation": item.compensation.value,
        }
        for item in manifest.contracts
    }
    rendered = json.dumps(
        contracts,
        indent=2,
        ensure_ascii=True,
        sort_keys=True,
    )
    digest = sha256_digest(manifest)
    return (
        '"""Generated by m365-compile-contracts; do not edit manually."""\n\n'
        "import json\n"
        "from typing import Any, Final\n\n"
        "CONTRACT_MANIFEST_DIGEST: Final = (\n"
        f"    {digest!r}\n"
        ")\n"
        "CONTRACT_EFFECT_MODEL_DIGEST: Final = (\n"
        f"    {model_digest!r}\n"
        ")\n"
        "CONTRACT_DEFINITIONS: Final[dict[str, dict[str, Any]]] = json.loads(\n"
        f"    r'''{rendered}'''\n"
        ")\n"
    )


def _permission_matrix(manifest: ContractManifest) -> str:
    lines = [
        "# Compiled contract matrix",
        "",
        "Generated from the signed, tenant-neutral global manifest.",
        (
            "Schema 1.0 effects are derived by the closed compiler mapping "
            "`GET → read`, `PATCH → update_properties`; ambiguous POST is "
            "rejected. Future schema 2.0 contracts must sign an explicit effect."
        ),
        "",
        (
            "| Contract | Tool | Effect | Graph call | Tier | Authorization | "
            "Delegated scopes |"
        ),
        "|---|---|---|---|---|---|---|",
    ]
    for item in manifest.contracts:
        scopes = "<br>".join(f"`{scope}`" for scope in item.permissions.delegated_scopes)
        lines.append(
            f"| `{item.id}` | `{item.tool_name}` | "
            f"`{contract_effect(item).value}` | "
            f"`{item.graph.method} {item.graph.endpoint}` | `{item.risk_tier.value}` | "
            f"`{item.authorization_mode.value}` | {scopes} |"
        )
    lines.extend(
        [
            "",
            "Permissions are informational build output. The server cannot add delegated",
            "permissions or grant tenant consent; an administrator must do that manually.",
            "",
        ]
    )
    return "\n".join(lines)


def load_identity_candidate(root: Path) -> ContractManifestV2:
    """Load the reviewed but unsigned Identity candidate source."""

    document = json.loads(
        (root / "contract-candidates/identity-slice.json").read_text()
    )
    manifest = parse_contract_manifest(document)
    if not isinstance(manifest, ContractManifestV2):
        raise ValueError("Identity candidate must use contract schema 2.0")
    if any(item.lifecycle_state.value != "candidate" for item in manifest.contracts):
        raise ValueError("Identity candidate source contains an active contract")
    return manifest


def _candidate_matrix(manifest: ContractManifestV2) -> str:
    lines = [
        "# Identity Slice candidate contract matrix",
        "",
        (
            "Generated from the unsigned schema-2.0 candidate manifest. These "
            "contracts are **not active MCP tools** and cannot execute Graph."
        ),
        "",
        (
            "| Contract | Lifecycle | Effect | Graph call | Tier | Authorization | "
            "Verification | License prerequisites | Official references |"
        ),
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for item in manifest.contracts:
        licenses = "<br>".join(item.license_prerequisites)
        references = "<br>".join(
            f"[Microsoft]({reference})" for reference in item.official_references
        )
        lines.append(
            f"| `{item.id}` | `{item.lifecycle_state.value}` | `{item.effect.value}` | "
            f"`{item.graph.method} {item.graph.endpoint}` | `{item.risk_tier.value}` | "
            f"`{item.authorization_mode.value}` | `{item.verification.value}` | "
            f"{licenses} | "
            f"{references}<br>verified `{item.verified_on}` |"
        )
    lines.extend(
        [
            "",
            "## Permission and role separation",
            "",
            (
                "The aggregate delegated-scope closure is shown separately from "
                "the reason each permission is needed. Scope categories can overlap."
            ),
            "",
            (
                "| Contract | Effect permissions | Preflight permissions | "
                "Readback permissions | Protected-object evidence permissions | "
                "Microsoft-supported least-privileged roles | "
                "Project-required operational role | Project rationale | "
                "Microsoft-supported evidence roles | "
                "Project-required evidence role | Evidence-role rationale |"
            ),
            "|---|---|---|---|---|---|---|---|---|---|---|",
        ]
    )
    for item in manifest.contracts:
        permissions = item.permissions

        def values(items: list[str]) -> str:
            return "<br>".join(f"`{value}`" for value in items) or "None"

        lines.append(
            f"| `{item.id}` | {values(permissions.effect_delegated_scopes)} | "
            f"{values(permissions.preflight_delegated_scopes)} | "
            f"{values(permissions.readback_delegated_scopes)} | "
            f"{values(permissions.protected_object_evidence_delegated_scopes)} | "
            f"{values(permissions.microsoft_supported_roles)} | "
            f"`{permissions.project_required_role}` | "
            f"{permissions.project_role_rationale} | "
            f"{values(permissions.microsoft_supported_evidence_roles)} | "
            f"`{permissions.project_required_evidence_role}` | "
            f"{permissions.project_evidence_role_rationale} |"
        )
    lines.extend(
        [
            "",
            "## Activation gate",
            "",
            "This candidate PR may merge while every contract remains inactive.",
            "All five operations require reviewed live-lab execution before signing.",
            "Any live-lab correction changes and invalidates the candidate digest.",
            "The external signer signs only the resulting final reviewed digest.",
            "A separate, small activation PR performs the direct cutover and adds the",
            "production signature and active artifacts. No candidate is registered as",
            "an MCP tool before that activation PR. Test keys cannot activate candidates.",
            "",
        ]
    )
    return "\n".join(lines)


def compile_identity_candidate_outputs(
    manifest: ContractManifestV2,
    *,
    active_manifest: ContractManifest,
    root: Path,
) -> dict[Path, bytes]:
    """Generate review-only artifacts that never feed runtime registration."""

    candidate_digest = sha256_digest(manifest)
    active_digest = sha256_digest(active_manifest)
    model_digest = effect_model_digest()
    contract_digests = {
        item.id: sha256_digest(item) for item in manifest.contracts
    }
    candidate_endpoints = sorted(
        {
            f"{item.graph.method} {item.graph.endpoint}"
            for item in manifest.contracts
        }
    )
    active_endpoints = sorted(
        {
            f"{item.graph.method} {item.graph.endpoint}"
            for item in active_manifest.contracts
        }
    )
    candidate_scopes = sorted(
        {
            scope
            for item in manifest.contracts
            for scope in item.permissions.delegated_scopes
        }
    )
    active_scopes = sorted(
        {
            scope
            for item in active_manifest.contracts
            for scope in item.permissions.delegated_scopes
        }
    )
    registry = {
        "schema_version": "1.0",
        "activation_state": "candidate",
        "manifest_schema_version": manifest.schema_version,
        "manifest_digest": candidate_digest,
        "effect_model_digest": model_digest,
        "contracts": {
            item.id: {
                "contract_digest": contract_digests[item.id],
                "effect": item.effect.value,
                "endpoint": item.graph.endpoint,
                "method": item.graph.method,
                "authorization_mode": item.authorization_mode.value,
                "risk_tier": item.risk_tier.value,
                "lifecycle_state": item.lifecycle_state.value,
                "maturity": item.maturity.value,
                "executor_id": item.executor_id.value,
                "resource_fence_id": item.resource_fence_id.value,
                "protected_object_policy_id": item.protected_object_policy_id.value,
                "verification_contract_id": item.verification_contract_id.value,
                "delegated_scopes": item.permissions.delegated_scopes,
                "operator_roles": item.permissions.operator_roles,
                "effect_delegated_scopes": (
                    item.permissions.effect_delegated_scopes
                ),
                "preflight_delegated_scopes": (
                    item.permissions.preflight_delegated_scopes
                ),
                "readback_delegated_scopes": (
                    item.permissions.readback_delegated_scopes
                ),
                "protected_object_evidence_delegated_scopes": (
                    item.permissions.protected_object_evidence_delegated_scopes
                ),
                "microsoft_supported_roles": (
                    item.permissions.microsoft_supported_roles
                ),
                "project_required_role": item.permissions.project_required_role,
                "project_role_rationale": item.permissions.project_role_rationale,
                "microsoft_supported_evidence_roles": (
                    item.permissions.microsoft_supported_evidence_roles
                ),
                "project_required_evidence_role": (
                    item.permissions.project_required_evidence_role
                ),
                "project_evidence_role_rationale": (
                    item.permissions.project_evidence_role_rationale
                ),
            }
            for item in manifest.contracts
        },
    }
    surface_diff = {
        "schema_version": "1.0",
        "active_manifest_digest": active_digest,
        "candidate_manifest_digest": candidate_digest,
        "activation_state": "candidate",
        "active_surface_unchanged": True,
        "candidate_endpoints": candidate_endpoints,
        "candidate_only_endpoints": sorted(set(candidate_endpoints) - set(active_endpoints)),
        "candidate_delegated_scopes": candidate_scopes,
        "candidate_only_delegated_scopes": sorted(
            set(candidate_scopes) - set(active_scopes)
        ),
        "runtime_registration_change": False,
    }
    candidate_provenance = {
        "schema_version": "1.0",
        "builder": "m365_secure_mcp.contract_compiler",
        "compiler_version": COMPILER_VERSION,
        "build_kind": "local-unattested",
        "distribution_status": "not-a-release",
        "release_attestation_status": "external-required",
        "activation_state": "candidate",
        "manifest_digest": candidate_digest,
        "effect_model_digest": model_digest,
        "signature_present": False,
        "runtime_tool_generation": False,
        "live_lab_review_status": "required-before-signing",
        "signing_eligible": False,
        "active_manifest_digest": active_digest,
        "registry_digest": sha256_digest(registry),
        "surface_diff_digest": sha256_digest(surface_diff),
    }
    sbom_binding = {
        "schema_version": "1.0",
        "activation_state": "candidate",
        "manifest_digest": candidate_digest,
        "effect_model_digest": model_digest,
        "candidate_provenance_digest": sha256_digest(candidate_provenance),
        "release_sbom_digest": (
            "sha256:"
            + hashlib.sha256(
                (root / "contract-artifacts/sbom.cdx.json").read_bytes()
            ).hexdigest()
        ),
        "release_attestation_status": "external-required",
        "signing_eligible": False,
    }
    signing_request = {
        "schema_version": "1.0",
        "status": "awaiting_reviewed_live_lab",
        "signing_eligible": False,
        "manifest_digest": candidate_digest,
        "effect_model_digest": model_digest,
        "intended_key_id": "m365-contracts-2026-07",
        "intended_public_fingerprint": "pending-external-inspection",
        "artifact_digests": {
            "candidate_registry": sha256_digest(registry),
            "graph_surface_diff": sha256_digest(surface_diff),
            "provenance": sha256_digest(candidate_provenance),
            "sbom_binding": sha256_digest(sbom_binding),
        },
        "tests_required": [
            "compiler-check",
            "current-and-historical-signature-verification",
            "candidate-activation-denial",
            "governance-v1-v2-v3-compatibility",
            "identity-recorded-playback",
            "reviewed-live-lab-all-five-operations",
            "privacy-and-secret-scan",
        ],
        "activation_sequence": [
            "merge-inactive-candidate-pr",
            "execute-and-review-live-lab-for-all-five-operations",
            "apply-corrections-and-regenerate-candidate-digest-if-needed",
            "sign-final-reviewed-digest-with-external-production-authority",
            "merge-separate-small-activation-pr",
        ],
        "candidate_tool_registration": False,
        "digest_invalidated_by_candidate_change": True,
        "graph_surface_diff": surface_diff,
        "review_reference": "pull-request-required-before-signing",
        "contains_private_material": False,
    }

    def encoded(value: object) -> bytes:
        return (
            json.dumps(value, indent=2, ensure_ascii=False, sort_keys=True) + "\n"
        ).encode()

    outputs = {
        root / "contract-candidates/generated-registry.json": encoded(registry),
        root / "contract-candidates/graph-surface-diff.json": encoded(surface_diff),
        root / "contract-candidates/provenance.json": encoded(candidate_provenance),
        root / "contract-candidates/sbom-binding.json": encoded(sbom_binding),
        root / "contract-candidates/signing-request.json": encoded(signing_request),
        root / "docs/IDENTITY_CANDIDATE_MATRIX.md": _candidate_matrix(manifest).encode(),
    }
    return outputs


def _generated_controls(
    manifest: ControlManifest,
    compatibility: ControlCompatibilityMetadata,
) -> str:
    definitions = {
        item.control_id: {
            "definition_version": item.definition_version,
            "title": item.title,
            "description": item.description,
            "evaluator_id": item.evaluator_id.value,
            "expected_condition": item.expected_condition.value,
            "lifecycle": item.lifecycle.model_dump(mode="json"),
            "evidence_requirements": [
                requirement.model_dump(mode="json")
                for requirement in item.evidence_requirements
            ],
            "mapping_ids": item.mapping_ids,
            "limitation_codes": [
                limitation.value for limitation in item.limitation_codes
            ],
            "operator_action_id": item.operator_action_id.value,
        }
        for item in manifest.controls
    }
    sources = {
        item.source_id: item.model_dump(mode="json")
        for item in manifest.sources
    }
    mappings = {
        item.mapping_id: item.model_dump(mode="json")
        for item in manifest.mappings
        if item.published
    }
    freshness = {
        item.control_id: {
            "definition_major_version": item.definition_major_version,
            "maximum_evidence_age_seconds": (
                item.maximum_evidence_age_seconds
            ),
        }
        for item in compatibility.controls
    }
    rendered_definitions = json.dumps(
        definitions,
        indent=2,
        ensure_ascii=True,
        sort_keys=True,
    )
    rendered_sources = json.dumps(
        sources,
        indent=2,
        ensure_ascii=True,
        sort_keys=True,
    )
    rendered_mappings = json.dumps(
        mappings,
        indent=2,
        ensure_ascii=True,
        sort_keys=True,
    )
    rendered_freshness = json.dumps(
        freshness,
        indent=2,
        ensure_ascii=True,
        sort_keys=True,
    )
    digest = sha256_digest(manifest)
    compatibility_digest = control_compatibility_digest(compatibility)
    return (
        "# ruff: noqa: E501\n"
        '"""Generated by m365-compile-contracts; do not edit manually."""\n\n'
        "import json\n"
        "from typing import Any, Final\n\n"
        f"CONTROL_LIBRARY_VERSION: Final = {manifest.library_version!r}\n"
        "CONTROL_MANIFEST_DIGEST: Final = (\n"
        f"    {digest!r}\n"
        ")\n"
        "CONTROL_COMPATIBILITY_SCHEMA_VERSION: Final = "
        f"{compatibility.schema_version!r}\n"
        "CONTROL_COMPATIBILITY_DIGEST: Final = (\n"
        f"    {compatibility_digest!r}\n"
        ")\n"
        "CONTROL_COMPATIBILITY_FRESHNESS: "
        "Final[dict[str, dict[str, Any]]] = json.loads(\n"
        f"    r'''{rendered_freshness}'''\n"
        ")\n"
        "CONTROL_DEFINITIONS: Final[dict[str, dict[str, Any]]] = json.loads(\n"
        f"    r'''{rendered_definitions}'''\n"
        ")\n"
        "CONTROL_FRAMEWORK_SOURCES: Final[dict[str, dict[str, Any]]] = "
        "json.loads(\n"
        f"    r'''{rendered_sources}'''\n"
        ")\n"
        "CONTROL_FRAMEWORK_MAPPINGS: Final[dict[str, dict[str, Any]]] = "
        "json.loads(\n"
        f"    r'''{rendered_mappings}'''\n"
        ")\n"
    )


def _control_matrix(
    manifest: ControlManifest,
    compatibility: ControlCompatibilityMetadata,
) -> str:
    freshness = {
        item.control_id: item.maximum_evidence_age_seconds
        for item in compatibility.controls
    }
    lines = [
        "# Compiled posture control matrix",
        "",
        "Generated from the independently signed, tenant-neutral control manifest.",
        "Definitions contain no customer severity, tenant selectors or executable rules.",
        (
            "The separate M1 freshness compatibility artifact is not signed control "
            "definition metadata. Governance v2 pins its canonical digest: "
            f"`{control_compatibility_digest(compatibility)}`."
        ),
        "",
        "| Control ID | Definition | Evaluator | Evidence dependency | "
        "Maximum evidence age | Intended result | Lifecycle |",
        "|---|---|---|---|---|---|---|",
    ]
    for item in manifest.controls:
        dependencies = "<br>".join(
            f"`{requirement.source_contract_id}`"
            for requirement in item.evidence_requirements
        )
        lines.append(
            f"| `{item.control_id}` | `{item.definition_version}` | "
            f"`{item.evaluator_id.value}` | {dependencies} | "
            f"`{freshness[item.control_id]}` seconds | "
            f"`{item.expected_condition.value}` | `{item.lifecycle.state.value}` |"
        )
    lines.extend(
        [
            "",
            "## Published framework mappings",
            "",
            "| Mapping | Source | Reference | Relationship | Technical | Organizational |",
            "|---|---|---|---|---|---|",
        ]
    )
    for mapping in manifest.mappings:
        if not mapping.published:
            continue
        lines.append(
            f"| `{mapping.mapping_id}` | `{mapping.source_id}` | "
            f"{mapping.reference} | `{mapping.relationship.value}` | "
            f"`{mapping.technical_coverage.value}` | "
            f"`{mapping.organizational_coverage.value}` |"
        )
    lines.extend(
        [
            "",
            "Mappings express bounded evidence relationships only. They do not certify",
            "legal, regulatory or organizational compliance. Unverified sources are not",
            "published by the compiler.",
            "",
        ]
    )
    return "\n".join(lines)


def _generated_playbooks(
    playbooks: PlaybookManifest,
    contracts: ContractManifest,
) -> str:
    definitions = {
        playbook.id: {
            "tool_name": playbook.tool_name,
            "module": playbook.module,
            "risk_tier": playbook.risk_tier.value,
            "authorization_mode": playbook.authorization_mode.value,
            "writes_permitted": playbook.writes_permitted,
            "failure_mode": playbook.failure_mode,
            "compensation": playbook.compensation.value,
            "nodes": [
                {
                    "id": node.id,
                    "contract_id": node.contract_id,
                    "depends_on": node.depends_on,
                }
                for node in playbook.ordered_nodes()
            ],
            "delegated_scopes": playbook.delegated_scope_closure(contracts),
            "operator_roles": playbook.operator_role_closure(contracts),
            "output_fields": playbook.output_fields,
        }
        for playbook in playbooks.playbooks
    }
    rendered = json.dumps(
        definitions,
        indent=2,
        ensure_ascii=True,
        sort_keys=True,
    )
    digest = sha256_digest(playbooks)
    return (
        '"""Generated by m365-compile-contracts; do not edit manually."""\n\n'
        "import json\n"
        "from typing import Any, Final\n\n"
        "PLAYBOOK_MANIFEST_DIGEST: Final = (\n"
        f"    {digest!r}\n"
        ")\n"
        "PLAYBOOK_DEFINITIONS: Final[dict[str, dict[str, Any]]] = json.loads(\n"
        f"    r'''{rendered}'''\n"
        ")\n"
    )


def _playbook_matrix(
    playbooks: PlaybookManifest,
    contracts: ContractManifest,
) -> str:
    lines = [
        "# Compiled playbook matrix",
        "",
        "Generated from the signed, tenant-neutral playbook manifest.",
        "",
        "| Playbook | Tool | Nodes | Tier | Authorization | Permission closure |",
        "|---|---|---|---|---|---|",
    ]
    for playbook in playbooks.playbooks:
        nodes = "<br>".join(
            f"`{node.id}` → `{node.contract_id}`"
            for node in playbook.ordered_nodes()
        )
        scopes = "<br>".join(
            f"`{scope}`"
            for scope in playbook.delegated_scope_closure(contracts)
        )
        lines.append(
            f"| `{playbook.id}` | `{playbook.tool_name}` | {nodes} | "
            f"`{playbook.risk_tier.value}` | "
            f"`{playbook.authorization_mode.value}` | {scopes} |"
        )
    lines.extend(
        [
            "",
            "The permission closure is the exact union of referenced compiled",
            "contracts. Playbooks cannot add scopes, Graph calls, or runtime tools.",
            "",
        ]
    )
    return "\n".join(lines)


def _dependency_components(root: Path) -> list[dict[str, Any]]:
    lock = tomllib.loads((root / "uv.lock").read_text())
    components: list[dict[str, Any]] = []
    seen: set[tuple[str, str]] = set()
    for package in lock["package"]:
        name = str(package["name"]).lower().replace("_", "-")
        version = str(package.get("version", ""))
        if (
            not version
            or name == "m365-secure-mcp"
            or not isinstance(package.get("source"), dict)
            or "registry" not in package["source"]
            or (name, version) in seen
        ):
            continue
        seen.add((name, version))
        components.append(
            {
                "type": "library",
                "bom-ref": f"pkg:pypi/{name}@{version}",
                "name": name,
                "version": version,
                "purl": f"pkg:pypi/{name}@{version}",
                "properties": [
                    {
                        "name": "m365-secure-mcp:source",
                        "value": "uv.lock",
                    }
                ],
            }
        )
    return sorted(
        components,
        key=lambda item: (str(item["name"]), str(item["version"])),
    )


def compile_outputs(
    manifest: ContractManifest,
    *,
    root: Path,
    playbooks: PlaybookManifest | None = None,
    controls: ControlManifest | None = None,
    control_compatibility: ControlCompatibilityMetadata | None = None,
) -> dict[Path, bytes]:
    playbooks = playbooks or load_global_playbook_manifest(manifest)
    controls = controls or load_global_control_manifest()
    compatibility = (
        control_compatibility
        if control_compatibility is not None
        else load_control_compatibility_metadata(controls)
    )
    compatibility.validate_manifest_binding(controls)
    manifest_digest = sha256_digest(manifest)
    playbook_manifest_digest = sha256_digest(playbooks)
    control_manifest_digest = sha256_digest(controls)
    compatibility_digest = control_compatibility_digest(compatibility)
    model_digest = effect_model_digest()
    model_document = effect_model_document()
    lock_digest = (
        "sha256:"
        + hashlib.sha256((root / "uv.lock").read_bytes()).hexdigest()
    )
    contract_digests = {
        item.id: sha256_digest(item)
        for item in manifest.contracts
    }
    playbook_digests = {
        item.id: sha256_digest(item)
        for item in playbooks.playbooks
    }
    control_digests = {
        item.control_id: sha256_digest(item)
        for item in controls.controls
    }
    tests = {
        "schema_version": "1.0",
        "manifest_digest": manifest_digest,
        "assertions": [
            {
                "contract_id": item.id,
                "method": item.graph.method,
                "endpoint": item.graph.endpoint,
                "input_fields": sorted(item.input_schema["properties"]),
                "delegated_scopes": item.permissions.delegated_scopes,
                "authorization_mode": item.authorization_mode.value,
                "risk_tier": item.risk_tier.value,
                "effect": contract_effect(item).value,
            }
            for item in manifest.contracts
        ],
    }
    contract_digest_document = {
        "schema_version": "1.0",
        "manifest_digest": manifest_digest,
        "effect_model_digest": model_digest,
        "contracts": contract_digests,
    }
    playbook_digest_document = {
        "schema_version": "1.0",
        "playbook_manifest_digest": playbook_manifest_digest,
        "playbooks": playbook_digests,
    }
    control_digest_document = {
        "schema_version": "1.0",
        "control_manifest_digest": control_manifest_digest,
        "control_library_version": controls.library_version,
        "control_compatibility_schema_version": compatibility.schema_version,
        "control_compatibility_digest": compatibility_digest,
        "controls": control_digests,
    }
    sbom_serial = uuid5(
        NAMESPACE_URL,
        (
            f"m365-secure-mcp:{manifest_digest}:"
            f"{playbook_manifest_digest}:{control_manifest_digest}:"
            f"{compatibility_digest}:{model_digest}:{lock_digest}"
        ),
    )
    package_version = str(
        tomllib.loads(
            (root / "pyproject.toml").read_text()
        )["project"]["version"]
    )
    sbom = {
        "bomFormat": "CycloneDX",
        "specVersion": "1.6",
        "serialNumber": f"urn:uuid:{sbom_serial}",
        "version": 1,
        "metadata": {
            "component": {
                "type": "application",
                "name": "m365-secure-mcp",
                "version": package_version,
                "properties": [
                    {
                        "name": "m365-secure-mcp:contract-effect-model-digest",
                        "value": model_digest,
                    },
                    {
                        "name": (
                            "m365-secure-mcp:"
                            "control-compatibility-digest"
                        ),
                        "value": compatibility_digest,
                    },
                    {
                        "name": (
                            "m365-secure-mcp:"
                            "control-manifest-digest"
                        ),
                        "value": control_manifest_digest,
                    },
                ],
            }
        },
        "components": _dependency_components(root),
    }
    provenance = {
        "schema_version": "1.0",
        "builder": "m365_secure_mcp.contract_compiler",
        "compiler_version": COMPILER_VERSION,
        "package_version": package_version,
        "source_repository": "https://github.com/bugroo/m365-secure-mcp",
        "source_revision": "release-attestation-required",
        "build_kind": "local-unattested",
        "distribution_status": "not-a-release",
        "release_attestation_status": "external-required",
        "manifest_digest": manifest_digest,
        "manifest_signature_required": True,
        "contract_effect_model_schema_version": (
            model_document["schema_version"]
        ),
        "contract_effect_model_digest": model_digest,
        "playbook_manifest_digest": playbook_manifest_digest,
        "playbook_manifest_signature_required": True,
        "control_manifest_digest": control_manifest_digest,
        "control_manifest_signature_required": True,
        "control_compatibility_schema_version": compatibility.schema_version,
        "control_compatibility_digest": compatibility_digest,
        "contract_digests_digest": sha256_digest(
            contract_digest_document
        ),
        "playbook_digests_digest": sha256_digest(
            playbook_digest_document
        ),
        "control_digests_digest": sha256_digest(
            control_digest_document
        ),
        "sbom_digest": sha256_digest(sbom),
        "dependency_lock_digest": lock_digest,
        "runtime_tool_generation": False,
    }

    def encoded(value: object) -> bytes:
        return (
            json.dumps(value, indent=2, ensure_ascii=False, sort_keys=True) + "\n"
        ).encode()

    outputs = {
        root / "src/m365_secure_mcp/_generated_contracts.py": (
            _generated_python(manifest).encode()
        ),
        root / "src/m365_secure_mcp/_generated_playbooks.py": (
            _generated_playbooks(playbooks, manifest).encode()
        ),
        root / "src/m365_secure_mcp/_generated_controls.py": (
            _generated_controls(controls, compatibility).encode()
        ),
        root / "docs/CONTRACT_MATRIX.md": _permission_matrix(manifest).encode(),
        root / "docs/PLAYBOOK_MATRIX.md": (
            _playbook_matrix(playbooks, manifest).encode()
        ),
        root / "docs/CONTROL_MATRIX.md": (
            _control_matrix(controls, compatibility).encode()
        ),
        root / "contract-artifacts/contract-digests.json": encoded(
            contract_digest_document
        ),
        root / "contract-artifacts/contract-effect-model.json": encoded(
            model_document
        ),
        root / "contract-artifacts/contract-tests.json": encoded(tests),
        root / "contract-artifacts/playbook-digests.json": encoded(
            playbook_digest_document
        ),
        root / "contract-artifacts/playbook-tests.json": encoded(
            {
                "schema_version": "1.0",
                "contract_manifest_digest": manifest_digest,
                "playbook_manifest_digest": playbook_manifest_digest,
                "assertions": [
                    {
                        "playbook_id": playbook.id,
                        "tool_name": playbook.tool_name,
                        "node_contract_ids": [
                            node.contract_id
                            for node in playbook.ordered_nodes()
                        ],
                        "delegated_scope_closure": (
                            playbook.delegated_scope_closure(manifest)
                        ),
                        "authorization_mode": (
                            playbook.authorization_mode.value
                        ),
                        "risk_tier": playbook.risk_tier.value,
                        "writes_permitted": playbook.writes_permitted,
                    }
                    for playbook in playbooks.playbooks
                ],
            }
        ),
        root / "contract-artifacts/control-digests.json": encoded(
            control_digest_document
        ),
        root / "contract-artifacts/control-tests.json": encoded(
            {
                "schema_version": "1.0",
                "control_manifest_digest": control_manifest_digest,
                "control_library_version": controls.library_version,
                "control_compatibility_schema_version": (
                    compatibility.schema_version
                ),
                "control_compatibility_digest": compatibility_digest,
                "assertions": [
                    {
                        "control_id": control.control_id,
                        "definition_version": control.definition_version,
                        "evaluator_id": control.evaluator_id.value,
                        "evidence_contract_ids": sorted(
                            {
                                requirement.source_contract_id
                                for requirement in control.evidence_requirements
                            }
                        ),
                        "expected_condition": control.expected_condition.value,
                        "lifecycle_state": control.lifecycle.state.value,
                        "maximum_evidence_age_seconds": (
                            compatibility.maximum_age(
                                control.control_id,
                                int(
                                    control.definition_version.split(".", 1)[0]
                                ),
                            )
                        ),
                        "mapping_ids": control.mapping_ids,
                    }
                    for control in controls.controls
                ],
            }
        ),
        root / "contract-artifacts/provenance.json": encoded(provenance),
        root / "contract-artifacts/sbom.cdx.json": encoded(sbom),
        root / "src/m365_secure_mcp/release_data/contract-digests.json": (
            encoded(contract_digest_document)
        ),
        root / "src/m365_secure_mcp/release_data/contract-effect-model.json": (
            encoded(model_document)
        ),
        root / "src/m365_secure_mcp/release_data/playbook-digests.json": (
            encoded(playbook_digest_document)
        ),
        root / "src/m365_secure_mcp/release_data/control-digests.json": (
            encoded(control_digest_document)
        ),
        root / "src/m365_secure_mcp/release_data/provenance.json": (
            encoded(provenance)
        ),
        root / "src/m365_secure_mcp/release_data/sbom.cdx.json": encoded(
            sbom
        ),
    }
    identity_candidate = load_identity_candidate(root)
    outputs.update(
        compile_identity_candidate_outputs(
            identity_candidate,
            active_manifest=manifest,
            root=root,
        )
    )
    return outputs


def write_outputs(outputs: dict[Path, bytes]) -> None:
    for path, payload in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(payload)


def check_outputs(outputs: dict[Path, bytes]) -> list[str]:
    mismatches: list[str] = []
    for path, expected in outputs.items():
        try:
            actual = path.read_bytes()
        except OSError:
            mismatches.append(str(path))
            continue
        if actual != expected:
            mismatches.append(str(path))
    return mismatches


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="m365-compile-contracts",
        description=(
            "Verify signed global manifests and generate deterministic internal "
            "contracts, controls, docs, tests, provenance, and CycloneDX SBOM."
        ),
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if committed generated artifacts differ from the signed manifest",
    )
    return parser


def main() -> None:
    args = _parser().parse_args()
    root = _repo_root()
    manifest = load_global_manifest()
    playbooks = load_global_playbook_manifest(manifest)
    controls = load_global_control_manifest()
    control_compatibility = load_control_compatibility_metadata(controls)
    outputs = compile_outputs(
        manifest,
        root=root,
        playbooks=playbooks,
        controls=controls,
        control_compatibility=control_compatibility,
    )
    if args.check:
        mismatches = check_outputs(outputs)
        if mismatches:
            raise SystemExit(
                "generated contract artifacts are stale:\n" + "\n".join(mismatches)
            )
        print(
            json.dumps(
                {
                    "status": "verified",
                    "manifest_digest": sha256_digest(manifest),
                    "contract_effect_model_digest": effect_model_digest(),
                    "playbook_manifest_digest": sha256_digest(playbooks),
                    "control_manifest_digest": sha256_digest(controls),
                    "control_compatibility_digest": (
                        control_compatibility_digest(
                            control_compatibility
                        )
                    ),
                    "artifacts": len(outputs),
                },
                indent=2,
            )
        )
        return
    write_outputs(outputs)
    print(
        json.dumps(
            {
                "status": "generated",
                "manifest_digest": sha256_digest(manifest),
                "contract_effect_model_digest": effect_model_digest(),
                "playbook_manifest_digest": sha256_digest(playbooks),
                "control_manifest_digest": sha256_digest(controls),
                "control_compatibility_digest": (
                    control_compatibility_digest(control_compatibility)
                ),
                "artifacts": len(outputs),
                "manifest_bytes": len(canonical_json(manifest)),
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
